// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wclnuznqkblmmntvufrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjbG51em5xa2JsbW1udHZ1ZnJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTA1NDMsImV4cCI6MjA2MTc2NjU0M30.-gQlEmZ5jaHTnOAFRU3u2EH_v7i4pcZ2Rw4CKirBX-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);